### ISSUE TITLE
NYMMS crashes when security tokens are invalid

### ISSUE THREAD

**Issue by synfinatic** [cloudtools/nymms#30]
This is really just a transient error.  We can just retry.

```
nymms_reactor stopped. Last 20 lines of /var/log/upstart/nymms_reactor.log:
[2015/02/07 06:02:57 UTC] pid:2199 DEBUG nymms.state.sdb_state sdb_state(save_state):55 - passive:agent_heartbeat.GCEStorageUpgrade - saving state: {'state_type': 1, 'state': 0, 'last_state_change': 1416254146, 'id': u'passive:agent_heartbeat.GCEStorageUpgrade', 'last_update': 1423288977}
Traceback (most recent call last):
  File "/usr/bin/nymms_reactor", line 30, in <module>
    visibility_timeout=visibility_timeout)
  File "/usr/lib/python2.7/dist-packages/nymms/daemon.py", line 14, in main
    self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nymms/reactor/Reactor.py", line 126, in run
    result.delete()
  File "/usr/lib/python2.7/dist-packages/nymms/data_types.py", line 49, in delete
    return self._origin.delete()
  File "/usr/lib/python2.7/dist-packages/boto/sqs/message.py", line 145, in delete
    return self.queue.delete_message(self)
  File "/usr/lib/python2.7/dist-packages/boto/sqs/queue.py", line 314, in delete_message
    return self.connection.delete_message(self, message)
  File "/usr/lib/python2.7/dist-packages/boto/sqs/connection.py", line 224, in delete_message
    return self.get_status('DeleteMessage', params, queue.id)
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1223, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.SQSError: SQSError: 403 Forbidden
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid.</Message><Detail/></Error><RequestId>7baf1b04-a820-5ba1-97a0-564b04f1352e</RequestId></ErrorResponse>

####################################################
Created by /etc/init/process_monitor.conf
```

**Comment by phobologic** [comment]
I think I'd rather avoid having logic in the code waiting for required credentials - leave that to the startup managers.
